"use client";
import { FormEvent, useState } from "react";

type State = { destination:string|null; check_in:string|null; check_out:string|null; adults:number|null; children:number; guests:number; budget_per_night:number|null; preferences:string[]; hold_id:string|null };
type Trace = { action:string; status?:string; input?:unknown; result?:unknown; error?:string };
type Recommendation = { room:string; property:string; rate:number; total?:number; nights?:number; capacity:number; available:boolean };
type Response = { session_id:string; assistant_message:string; booking_state:State; recommendations:Recommendation[]; trace:Trace[]; next_action:string };
type Message = { role:"user"|"assistant"; content:string };
const initial: State = { destination:null, check_in:null, check_out:null, adults:null, children:0, guests:0, budget_per_night:null, preferences:[], hold_id:null };

export default function Home() {
  const [sessionId,setSessionId] = useState<string|null>(null); const [input,setInput] = useState(""); const [loading,setLoading] = useState(false); const [state,setState] = useState(initial); const [recommendations,setRecommendations] = useState<Recommendation[]>([]); const [nextAction,setNextAction] = useState("ask_for_booking_details"); const [trace,setTrace] = useState<Trace[]>([]);
  const [messages,setMessages] = useState<Message[]>([{role:"assistant",content:"Hi, I’m StayMind. Tell me where and when you’d like to stay, and I’ll find a verified option."}]);
  async function send(event:FormEvent) { event.preventDefault(); const message=input.trim(); if(!message||loading)return; setInput(""); setLoading(true); setMessages(current=>[...current,{role:"user",content:message}]);
    try { const result=await fetch("http://localhost:8000/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,session_id:sessionId})}); if(!result.ok)throw new Error("The booking agent is unavailable."); const data:Response=await result.json(); setSessionId(data.session_id); setState(data.booking_state); setRecommendations(data.recommendations); setNextAction(data.next_action); setTrace(data.trace); setMessages(current=>[...current,{role:"assistant",content:data.assistant_message}]); }
    catch(error) { setMessages(current=>[...current,{role:"assistant",content:error instanceof Error?error.message:"Something went wrong."}]); } finally { setLoading(false); }
  }
  const value=(item:string|null) => item || "Not provided";
  return <main className="shell"><header className="topbar"><div><p className="eyebrow">StayMind AI</p><h1 className="title">Your stay, thoughtfully found.</h1></div><span className="status">Agent online</span></header><div className="grid"><section className="panel chat"><div className="messages">{messages.map((message,index)=><div className={`message ${message.role}`} key={index}><span className="avatar">{message.role==="user"?"You":"✦"}</span><div className="bubble">{message.content}</div></div>)}{loading&&<div className="message assistant"><span className="avatar">✦</span><div className="bubble">Checking availability and pricing...</div></div>}</div><form className="composer" onSubmit={send}><input value={input} onChange={event=>setInput(event.target.value)} placeholder="Goa next weekend for 3 people" aria-label="Message"/><button className="send" disabled={loading} aria-label="Send message">↑</button></form></section><aside className="side"><section className="panel"><h2 className="section-title">Booking details</h2><dl className="facts"><div className="fact"><dt>Destination</dt><dd>{value(state.destination)}</dd></div><div className="fact"><dt>Dates</dt><dd>{state.check_in&&state.check_out?`${state.check_in} → ${state.check_out}`:"Not provided"}</dd></div><div className="fact"><dt>Guests</dt><dd>{state.guests?`${state.guests} total`:"Not provided"}</dd></div><div className="fact"><dt>Budget</dt><dd>{state.budget_per_night?`₹${state.budget_per_night.toLocaleString()}/night`:"Not provided"}</dd></div><div className="fact"><dt>Preferences</dt><dd>{state.preferences.length?state.preferences.join(", "):"None yet"}</dd></div>{state.hold_id&&<div className="fact"><dt>Hold</dt><dd>{state.hold_id}</dd></div>}</dl></section><section className="panel"><h2 className="section-title">Next action</h2><p className="empty">{nextAction.replaceAll("_"," ")}</p></section>{recommendations.length>0&&<section className="panel"><h2 className="section-title">Verified options</h2><div className="trace">{recommendations.map((item,index)=><div className="trace-item" key={item.room}><strong>{index+1}. {item.room}</strong><br/>{item.property}<br/>₹{item.rate.toLocaleString()}/night · ₹{item.total?.toLocaleString()} estimated total</div>)}</div></section>}<section className="panel"><h2 className="section-title">Agent activity</h2>{trace.length?<div className="trace">{trace.map((item,index)=><details className="trace-item" key={`${item.action}-${index}`}><summary><span style={{color:item.status==="error"?"#b34c42":"#2f765e"}}>{item.status==="error"?"×":"✓"}</span> {item.action}</summary><pre>{JSON.stringify({input:item.input,result:item.result,error:item.error},null,2)}</pre></details>)}</div>:<p className="empty">Tool calls and validation results will appear here after your first request.</p>}</section></aside></div></main>;
}